services:
  postgres:
    image: postgres:16-alpine
    container_name: vizroom-postgres
    restart: always
    environment:
      - POSTGRES_USER=vizroom
      - POSTGRES_PASSWORD=vizroom
      - POSTGRES_DB=vizroom
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: